server:
  hostname: localhost
  port: ${PORT:8189}
  servlet:
    context-path: /
spring:
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test?currentSchema=command_project
    username: postgres
    password: n7g2phk2
    flyway:
      baseline-on-migrate: true
  jackson:
    serialization:
      indent_output: true
