server:
  port: 8189
  servlet:
    context-path: /command-project
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=command_project_v2
    username: postgres
    password: admin
    flyway:
      baseline-on-migrate: true
  jackson:
    serialization:
      indent_output: true