create table orders_tbl (
        id int8 not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sender varchar(255),
        receiver varchar(255),
        created timestamp,
        order_status varchar(255),
        user_id int8
    );

create table order_details_tbl (
        id int8 not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        number_of_boxes int8,
        comment TEXT,
        order_id int8
        );

create table shipment_details_tbl (
        id int8 not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        driver_name varchar(255),
        car_number varchar(255),
        shipment_date timestamp,
        delivery_date timestamp,
        order_id int8
        );

create table users_tbl (
        id int8 not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username varchar(255),
        password varchar(255),
        email varchar(255),
        role varchar(255)
        );

alter table if exists order_details_tbl
    add constraint order_details_fk_order
    foreign key (order_id) references orders_tbl;

alter table if exists shipment_details_tbl
    add constraint shipment_details_fk_order
    foreign key (order_id) references orders_tbl;

alter table if exists orders_tbl
    add constraint user_fk_order
    foreign key (user_id) references users_tbl;
